#!/bin/bash

###############################################################################
#
# RNA-seq quantification pipeline (simplified for laptop use)
#
# This script does two things for each sample:
#   1. Quality-trims paired-end FASTQ files using fastp
#   2. Quantifies transcript abundance using kallisto
#
# Before running this script, you need to:
#   - Install fastp:    conda install -c bioconda fastp
#   - Install kallisto: conda install -c bioconda kallisto
#   - Build a kallisto index from your reference transcriptome:
#       kallisto index -i my_transcriptome.idx my_transcriptome.fa
#
# Usage:
#   bash rna_seq_quantification.sh
#
###############################################################################

###############################################################################
# PARAMETERS — edit these to match your experiment
###############################################################################

# Number of CPU threads to use. 4 is a good comprimise for most laptops, but it really depends on your chip. Figure out how many cores you have available.
THREADS=4

# Number of bootstrap samples for kallisto. Use ~ #threads for testing,
# increase to 100 for a final/publishable analysis.
BOOTSTRAPS=4

# Minimum read length after trimming. Reads shorter than this are discarded.
MIN_READ_LENGTH=36

# Mean quality threshold for the sliding window trimmer in fastp.
# Bases below this quality at the 3' end are trimmed.
QUALITY_THRESHOLD=20

# Library strandedness for kallisto. Options:
#   --rf-stranded   : reverse-stranded (e.g., dUTP, most Illumina kits)
#   --fr-stranded   : forward-stranded
#   (leave empty)   : unstranded
# If you don't know, test all options ans see the percentage of mapped reads
STRANDEDNESS="--rf-stranded"

# Path to the kallisto transcriptome index you built (see instructions above).
# use the ones generated by the kallisto team, https://github.com/pachterlab/kallisto-transcriptome-indices/releases/tag/v1
# use the standard, for example mouse_index_standard.tar.xz for mouse
KALLISTO_INDEX="/path/to/my_transcriptome.idx"

# Directory containing your raw FASTQ files, organized as:
#   raw_data/
#     sample_A/
#       sample_A_rep1_R1.fastq.gz   sample_A_rep1_R2.fastq.gz
#       sample_A_rep2_R1.fastq.gz   sample_A_rep2_R2.fastq.gz
#       ...
#     sample_B/
#       ...
INPUT_DIR="./raw_data"

# Directory where all results will be saved.
OUTPUT_DIR="./results"

###############################################################################
# STEP 0 — Verify that tools are installed
###############################################################################

echo "============================================="
echo "Checking that required tools are installed..."
echo "============================================="

if ! command -v fastp &> /dev/null; then
    echo "ERROR: fastp is not installed or not in your PATH."
    echo "Install it with: conda install -c bioconda fastp"
    exit 1
fi

if ! command -v kallisto &> /dev/null; then
    echo "ERROR: kallisto is not installed or not in your PATH."
    echo "Install it with: conda install -c bioconda kallisto"
    exit 1
fi

echo "fastp version:    $(fastp --version 2>&1)"
echo "kallisto version:  $(kallisto version 2>&1)"
echo ""

# Check that the kallisto index exists
if [ ! -f "$KALLISTO_INDEX" ]; then
    echo "ERROR: Kallisto index not found at: $KALLISTO_INDEX"
    echo "Build one with: kallisto index -i my_transcriptome.idx my_transcriptome.fa"
    exit 1
fi

###############################################################################
# STEP 1 — Detect samples (each subfolder in INPUT_DIR is one sample)
###############################################################################

echo "============================================="
echo "Detecting samples in: $INPUT_DIR"
echo "============================================="

# Find all subdirectories inside INPUT_DIR. Each one is treated as a sample.
SAMPLES=($(find "$INPUT_DIR" -mindepth 1 -maxdepth 1 -type d | sort))

if [ ${#SAMPLES[@]} -eq 0 ]; then
    echo "ERROR: No sample folders found in $INPUT_DIR"
    exit 1
fi

echo "Found ${#SAMPLES[@]} sample(s):"
for s in "${SAMPLES[@]}"; do
    echo "  - $(basename "$s")"
done
echo ""

# Create the output directory if it doesn't exist yet
mkdir -p "$OUTPUT_DIR"

###############################################################################
# STEP 2 — Process each sample
###############################################################################

for SAMPLE_DIR in "${SAMPLES[@]}"; do

    SAMPLE_NAME=$(basename "$SAMPLE_DIR")

    echo "============================================="
    echo "Processing sample: $SAMPLE_NAME"
    echo "============================================="

    # -------------------------------------------------------------------
    # 2a. Find the paired-end FASTQ files for this sample
    # -------------------------------------------------------------------

    # We look for files ending in .fq.gz or .fastq.gz.
    # R1 files contain "R1" or "_1" in their name; R2 files contain "R2" or "_2".
    R1_FILES=($(ls "$SAMPLE_DIR"/*R1*.f*q.gz "$SAMPLE_DIR"/*_1.f*q.gz 2>/dev/null | sort -u))
    R2_FILES=($(ls "$SAMPLE_DIR"/*R2*.f*q.gz "$SAMPLE_DIR"/*_2.f*q.gz 2>/dev/null | sort -u))

    echo "  R1 files found: ${#R1_FILES[@]}"
    for f in "${R1_FILES[@]}"; do echo "    $f"; done

    echo "  R2 files found: ${#R2_FILES[@]}"
    for f in "${R2_FILES[@]}"; do echo "    $f"; done

    # Sanity check: R1 and R2 counts must match
    if [ ${#R1_FILES[@]} -ne ${#R2_FILES[@]} ]; then
        echo "  ERROR: Unequal number of R1 and R2 files. Skipping this sample."
        echo ""
        continue
    fi

    if [ ${#R1_FILES[@]} -eq 0 ]; then
        echo "  ERROR: No FASTQ files found. Skipping this sample."
        echo ""
        continue
    fi

    # -------------------------------------------------------------------
    # 2b. Run fastp on each pair of FASTQ files (one pair = one replicate)
    # -------------------------------------------------------------------

    # We will collect the names of the cleaned files so kallisto can use them.
    CLEAN_FILES=()

    for i in "${!R1_FILES[@]}"; do

        REP=$((i + 1))
        R1="${R1_FILES[$i]}"
        R2="${R2_FILES[$i]}"

        # Define output file names for the cleaned reads
        CLEAN_R1="$OUTPUT_DIR/${SAMPLE_NAME}_rep${REP}_clean_R1.fq.gz"
        CLEAN_R2="$OUTPUT_DIR/${SAMPLE_NAME}_rep${REP}_clean_R2.fq.gz"

        # Define report file names
        HTML_REPORT="$OUTPUT_DIR/${SAMPLE_NAME}_rep${REP}_fastp_report.html"
        JSON_REPORT="$OUTPUT_DIR/${SAMPLE_NAME}_rep${REP}_fastp_report.json"

        echo ""
        echo "  Running fastp on replicate $REP ..."

        # Build the fastp command, print it, then run it
        FASTP_CMD="fastp \
-i $R1 \
-I $R2 \
-o $CLEAN_R1 \
-O $CLEAN_R2 \
--thread $THREADS \
--detect_adapter_for_pe \
--trim_poly_g \
--trim_poly_x \
--cut_tail \
--cut_window_size 4 \
--cut_mean_quality $QUALITY_THRESHOLD \
--length_required $MIN_READ_LENGTH \
-h $HTML_REPORT \
-j $JSON_REPORT"

        echo "  Command:"
        echo "  $FASTP_CMD"
        echo ""
        eval "$FASTP_CMD"

        # Collect the cleaned files for kallisto (R1 and R2 interleaved)
        CLEAN_FILES+=("$CLEAN_R1" "$CLEAN_R2")

    done

    # -------------------------------------------------------------------
    # 2c. Run kallisto to quantify transcript expression
    # -------------------------------------------------------------------
    #
    # kallisto uses "pseudoalignment" — it doesn't produce a BAM file.
    # Instead, it directly estimates transcript-level abundances, which
    # is much faster than traditional align-then-count approaches.
    #
    # The output folder will contain:
    #   abundance.tsv  — human-readable table of counts and TPMs
    #   abundance.h5   — binary file used by sleuth for differential expression
    #   run_info.json  — metadata about the run
    #
    # -------------------------------------------------------------------

    KALLISTO_OUT="$OUTPUT_DIR/kallisto_${SAMPLE_NAME}"

    # Build the kallisto command, print it, then run it
    KALLISTO_CMD="kallisto quant \
-i $KALLISTO_INDEX \
-o $KALLISTO_OUT \
-t $THREADS \
-b $BOOTSTRAPS \
$STRANDEDNESS \
--verbose \
${CLEAN_FILES[*]}"

    echo ""
    echo "  Running kallisto quantification ..."
    echo "  Command:"
    echo "  $KALLISTO_CMD"
    echo ""
    eval "$KALLISTO_CMD"

    echo ""
    echo "  Done with sample: $SAMPLE_NAME"
    echo ""

done

###############################################################################
# STEP 3 — Summary
###############################################################################

echo "============================================="
echo "All samples processed!"
echo "============================================="
echo ""
echo "Results are in: $OUTPUT_DIR"
echo ""
echo "For each sample you will find:"
echo "  - fastp HTML reports (open in a browser to inspect read quality)"
echo "  - a kallisto_<sample>/ folder with abundance.tsv (your counts)"
echo ""
echo "Next steps:"
echo "  1. Open the fastp HTML reports and check read quality."
echo "  2. Load the kallisto output into R using tximport or sleuth"
echo "     for differential expression analysis."
echo ""
